### ISSUE TITLE
promise::resolve is thread-safe?

### ISSUE THREAD

**Issue by AimplainLeo** [addisonElliott/HttpServer#14]
Great repo, could you teach me that resolve is threadsafe?

**Comment by addisonElliott** [comment]
QtPromise is used for promises in this library. The thread safety declaration is here: https://qtpromise.netlify.app/qtpromise/thread-safety.html

Fundamentally, I believe it relies on the Qt event loop which is thread safe if used correctly.

**Comment by AimplainLeo** [comment]
Thanks Elliot. If could please show me the right method for processing heavy task with other module (such as ObjectDetection  -OD- module - which run in other thread), without run qconcurrent for promise ( i cannot init this module alot of times, only one OD instance for whole project). Now, i can use async with timeout for send result. But it is not useful if processing time in OD is less or more than time out of task. Thank you very much!

**Comment by addisonElliott** [comment]
So, I'll provide a simplified example of what I do. I use HttpServer in a production application and I have blocking code that I run on a separate thread that is promisified.

Fundamentally, I want to point out this question is unrelated to this library however. Given that, I'm going to close this issue as well.

See the below Gist for an example of how you can do this: https://gist.github.com/addisonElliott/183f61b8594d294a5bb8d7b6486cf492

**Note that this example won't work as-is. It's just meant to demonstrate the concept.**

**Details**

* Qt's event loop is thread safe is used properly. So, I rely on that to communicate between the threads. Note that **no** data is shared between the threads **except** via the Qt event loop. Otherwise, it wouldn't be safe.
* WorkerThread is the class that starts the separate thread that processes various things. The main thread should initiate `WorkerThread`. 
* The `Worker` class has a list of slots that are executed on the separate thread. This is only meant to be used internally by `WorkerThread`.
* WorkerThread has the helper function `execAsyncPromise` that invokes a given slot in the `Worker` class on the separate thread.
* `WorkerThread::setControllersOffline()` - This function creates a promise that will execute the blocking function on `Worker`
* `Worker::setControllersOffline()` - This function is executed on the separate thread and can be blocking.

**Comment by AimplainLeo** [comment]
Wow, thank you very much!
